### ISSUE TITLE
[BUG] Changing messages do not work "messages.yml"

### ISSUE THREAD

**Issue by jeanlorencini** [TommyT0mmY/DrugDealing-plugin#1]
I am translating as messages from the messages.yml file but when the server was restarted the messages are not changed

**Comment by TommyT0mmY** [comment]
What's the version of the server? Which messages didn't load?

**Comment by TommyT0mmY** [comment]
Seems fixed by commit [cbc2957](https://github.com/TommyT0mmY/DrugDealing-plugin/commit/cbc2957044eb2426fddf17bde1b83705ed8c406f)

**Comment by TommyT0mmY** [comment]
Closed by cbc2957044eb2426fddf17bde1b83705ed8c406f
